version: "3.7"
services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: g2i-node-gonzachr
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    image: g2i-node-gonzachr
    depends_on:
      - db
    ports:
      - '4000:4000'